# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MaxMin <- function(A, B) {
    .Call(`_pkcpp_MaxMin`, A, B)
}

MxM <- function(A, B) {
    .Call(`_pkcpp_MxM`, A, B)
}

SearchMax <- function(x) {
    .Call(`_pkcpp_SearchMax`, x)
}

SearchMin <- function(x) {
    .Call(`_pkcpp_SearchMin`, x)
}

addC <- function(A, x) {
    .Call(`_pkcpp_addC`, A, x)
}

addR <- function(A, x) {
    .Call(`_pkcpp_addR`, A, x)
}

